// File generated by FlutterFire CLI.
// WARNING: NEVER COMMIT THIS FILE TO A PUBLIC REPOSITORY!
// It contains sensitive API keys and IDs for Firebase.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjHA2kJQIt8sxtVUJAOzMXIgz0FDQp1lw',
    appId: '1:1062436758460:web:df4155c095ec2692bb81b9',
    messagingSenderId: '1062436758460',
    projectId: 'la-familia-5d9f5',
    authDomain: 'la-familia-5d9f5.firebaseapp.com',
    storageBucket: 'la-familia-5d9f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJlzJW_SZyDY_JTJd3BzPauqhVR_B4FaM',
    appId: '1:1062436758460:android:d753e6aee97cca85bb81b9',
    messagingSenderId: '1062436758460',
    projectId: 'la-familia-5d9f5',
    storageBucket: 'la-familia-5d9f5.firebasestorage.app',
  );
}
